### ISSUE TITLE
無法寫入布林值

### ISSUE THREAD

**Issue by faustfu** [wendy512/iec61850#13]
測試發現 Client.Write 無法寫入布林值的原因是 Client.GetVariableSpecType 尚未實作相關型態，希望能補上相關實作，ex:
```
    case Boolean:
        return mmsType, nil
```

**Comment by wendy512** [comment]
Boolean类型已支持，其他类型也一并支持了，请更新到最新版本`go get -u github.com/wendy512/iec61850@v1.0.5`
